In [2]:
from google.colab import files
uploaded = files.upload()

Saving Dataset for Data Analytics (3).xlsx to Dataset for Data Analytics (3).xlsx

In [3]:
import pandas as pd

df = pd.read_excel("Dataset for Data Analytics (3).xlsx")

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [7]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [8]:
Q1 = df["TotalPrice"].quantile(0.25)
Q3 = df["TotalPrice"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_clean = df[(df["TotalPrice"] >= lower_bound) & (df["TotalPrice"] <= upper_bound)]

df_clean.shape

(1192, 14)

In [9]:
from scipy import stats
import numpy as np

z_scores = np.abs(stats.zscore(df["TotalPrice"]))

df_z = df[z_scores < 3]
df_z.shape

(1200, 14)

In [10]:
df["PricePerItem"] = df["TotalPrice"] / df["Quantity"]

In [11]:
df["HighValueOrder"] = df["TotalPrice"].apply(lambda x: 1 if x > df["TotalPrice"].mean() else 0)

In [13]:
def size_category(q):
    if q <= 2:
        return "Small"
    elif q <= 5:
        return "Medium"
    else:
        return "Large"

df["OrderSizeCategory"] = df["Quantity"].apply(size_category)

In [14]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,PricePerItem,HighValueOrder,OrderSizeCategory
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,570.62,1,Medium
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,151.35,0,Small
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,550.68,1,Medium
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,273.19,0,Small
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,626.01,1,Medium

In [15]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode           0
ReferralSource       0
TotalPrice           0
PricePerItem         0
HighValueOrder       0
OrderSizeCategory    0
dtype: int64